name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d412f249affa84b2f376b27d744f80a244370e5c22eea298c1346cda183a9216"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
