name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "383f331bbda447c9ef9de97fc3fe720a444b135c76c9719bfc0085a79074d2a3"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
