name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c38316e6c5ca2fc14950ca96dd38c2dc6cb991876e2ac794af7057ec97745f8c"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
