name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b816f67ae5787d352ebac4a2c87c46e304dbd1309718f5c31ed6d0cdaef66c1f"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
