name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3d9b18ec2e44efded9025dd7f9d51459e964e97cb4fc655378ea4636929caf4"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
