name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fc420c892f06d73276d27623b32e141f741f1c62678ddc06014785fe8af56f5"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
