name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f91eca98607e6b3fd525fab4b8aefac35602952f29f49776b79bbe2acb7934ff"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
