name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8cfe629b7afca660bd91fb573604cbe0c81c581ea8008d2b4778b1a15c0faa7"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
