name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ab828ecc024b5fce475a131a393897077ccc245cdb9a3f175bf8fd38bd52381"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
