name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "662960198a9c1bae5e33aafbfe231e5d0870112aa26a266376271553a3668996"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
