name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cec57f074b9204405abe215314ea947bfed43abcbbffd291f4e47609869aa1c"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
