name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43dade1338a772a467390275e24f22918bc73985ec6068575803a6d57fc6c2a6"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
