name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6d87414eb361bc94584f6ac899b68584a818d2e1f05dfc3ecc59a912507fb10"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
