name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2acf5d12a9eef804fdb3f90f8b67bb5b0fc74b077e55f611d0d181b84cbb3f4"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
