name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5b6bc932666cdc8d55fab706f034895c43f390276432f7e4c7a25c8919e6f6e"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
