name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "344978115a14729e080714ed63862b50231eb705a2fa65c6f693c967dcb849bc"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
