name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2a17f976de17f150e62e0338982c8e7b32fd0c028c7a8b5d68d9697b2e59b7e"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
