name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96469a5d8069d8e76ec2747640243abfff6c52707402b923e7452567e73b40a0"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
