name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95b2e30ba095e7f3f3e91068f424a805555522e89bc39e64e72889e9bdbce7ee"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
