name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1705b55224115cf36075e7d2bc6bd429d824cd5a724ea5a17246814210e42fbb"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
