name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85be1ba0550946fb2c610981b96d96cc4d8608dbafb8f2a850e96009ddd94bce"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
