name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf7773f3f64492632268508ea42e5aee04d7aafd965781b87fe0e244bfb4cc25"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
