name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eecf5411b558f365a02d622aca77564a4c08b33bad3b743d5ed5d7ef36e53540"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
