name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26feacc5269b8ede0f8bb2a8a531d0ceedcccb86209bc6cf1198a637eb52afa1"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
