name = "Refined_Pack"
author = "Funny_Bone_Man"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "715fba213f9ebab11a70b9289d282cda2b2dd935a65ec0865baa0aea40798510"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
